# Copyright 2017-present Open Networking Foundation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
version: '2'

services:

 onos:
  image: "voltha-mwc-2019-onos:latest"
  #image: "voltha-onos:latest"
  #image: "local-onos:local-apps"
  ports:
   - "8101:8101" # ssh
   - "6640:6640" # OF
   - "6653:6653" # OF
   - "8181:8181" # UI
   - "9876:9876" # ???
   - "5005:5005" # Intelli-J Idea debugging
  environment:
   ONOS_APPS: 'drivers,openflow-base'
   KARAF_DEBUG: 1
  networks:
    authnet:
     ipv4_address: 172.25.0.200

networks:
  authnet:
    driver: bridge
    ipam:
      config:
      - subnet: 172.25.0.0/24
